spring:
  activemq:
    broker-url: tcp://你的主机ip:61617
    user: admin
    password: admin
    pool:
      # 使用flase,此处改为true报错，不清楚什么原因
      enabled: false
      max-connections: 10
  redis:
    database: 0
    host: 你的主机ip
    port: 6379
    password: password
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
    timeout: 20000ms

queueName: sms
AccessKeyID: 你的accesskid
AccessKeySecret: 你的密钥
signName: 你的签名
templateCode: 你的模板名